services:
  hpwv:
    image: buettner123/hpwv
    build:
      context: .
    environment:
      - NODE_ENV=production
    volumes:
      - ./public/config.js:/usr/share/nginx/html/config.js
    ports:
      - '80:80'
